### ISSUE TITLE
When destroy LottieAnimation, should call destroy on LottieResource 

### ISSUE THREAD

**Issue by yangfengzzz** [ant-galaxy/engine-lottie#51]
LottieAnimation will destroy all texture but the LottieResource resource will leave in the cache of resource manager. when load the same url again, the cache will work without texture

Now I have to call it by hand:
```
this._currentEntity.getComponent(LottieAnimation).resource.destroy();
this._currentEntity.destroy();
```

**Comment by eyworldwide** [comment]
That's right. In this PR https://github.com/ant-galaxy/engine-lottie/pull/49 we only destroy textures, the **resource** should also be destroyed.
